language: python
python: 3.5
sudo: false
cache: pip

install:
  - pip install -e .

script:
  - python -m resonancesml choose-clf -l input/librations/first50_librated_asteroids_4_-2_-1 -c syn

  - python -m resonancesml influence-fields -c syn --clf="DT 0" -l input/librations/first50_librated_asteroids_4_-2_-1
  - python -m resonancesml influence-fields -c syn --clf="KNN 0" -l input/librations/first50_librated_asteroids_4_-2_-1
  - python -m resonancesml influence-fields -c syn --clf="XGB 0" -l input/librations/first50_librated_asteroids_4_-2_-1

  - python -m resonancesml classify-all -l input/librations/first50_librated_asteroids_4_-2_-1 -a input/librations/all_librated_asteroids_4_-2_-1  -c syn --clf="KNN 0" --clf="DT 0" 2 3 4 5 -v
  - python -m resonancesml classify-all -l input/librations/first100_librated_asteroids_4_-2_-1 -a input/librations/all_librated_asteroids_4_-2_-1  -c syn --clf="KNN 0" --clf="DT 0" 2 3 4 5 -v
  - python -m resonancesml classify-all -l input/librations/first200_librated_asteroids_4_-2_-1 -a input/librations/all_librated_asteroids_4_-2_-1  -c syn --clf="KNN 0" --clf="DT 0" 2 3 4 5 -v

  - python -m resonancesml classify-all -l input/librations/first50_librated_asteroids_4_-2_-1 -a input/librations/all_librated_asteroids_4_-2_-1  -c syn --clf="KNN 0" --clf="DT 0" 2 3 5 -v
  - python -m resonancesml classify-all -l input/librations/first100_librated_asteroids_4_-2_-1 -a input/librations/all_librated_asteroids_4_-2_-1  -c syn --clf="KNN 0" --clf="DT 0" 2 3 5 -v
  - python -m resonancesml classify-all -l input/librations/first200_librated_asteroids_4_-2_-1 -a input/librations/all_librated_asteroids_4_-2_-1  -c syn --clf="KNN 0" --clf="DT 0" 2 3 5 -v

  - python -m resonancesml get_optimal_parameters -c syn --clf=KNN -l input/librations/4J-2S-1-pure/first200

  - python -m resonancesml dump-config

after_success:
  - wc -l resonanceml-out/4J-2S-1
