catalogs:
  synthetic: all.syn
  orbital: allnum.cat
  property: allnum.pro

resonance_tables:
  js: matrix-js.res

librations_folders:
  "4J-2S-1": "4J-2S-1"
  "all-JS": libration_asteroids_JS

classifiers_for_comparing:
  - {report_name: 'K neighbors', preset: {name: KNN, params: {weights: 'distance', p: 1, n_neighbors: 7, n_jobs: 4}}}
  - {report_name: 'Gradient boosting (10 trees)', preset: {name: GB, params: {n_estimators: 10, learning_rate: 0.85}}}
  - {report_name: 'Gradient boosting (50 trees)', preset: {name: GB, params: {n_estimators: 50, learning_rate: 0.85}}}
    #n_estimators: 7, learning_rate: 0.6, min_samples_split: 33240),
  - {report_name: 'Decision tree', preset: {name: DT, params: {random_state: 241}}}
  - {report_name: 'Logistic regression', preset: {name: LR, params: {C: 0.00001, penalty: 'l1', n_jobs: 4}}}
  - report_name: 'XGBClassifier'
    preset:
      name: XGB
      params:
        n_estimators: 100
        max_depth: 2
        nthread: 4
        gamma: 2
        subsample: 0.2
        colsample_bytree: 0.5
        learning_rate: 2

classifiers:
  KNN:
    - {weights: 'distance', p: 1, n_jobs: 4, n_neighbors: 7}
    - metric: euclidean
    - metric: knezevic
    - weights: distance
      n_jobs: 1
      algorithm: ball_tree
      p: 2
    - weights: distance
      n_jobs: 1
      algorithm: ball_tree
      metric: knezevic
  GB:
    - n_estimators: 7
      learning_rate: 0.6
      min_samples_split: 150
    - n_estimators: 10
      learning_rate: 0.85
    - n_estimators: 50
      learning_rate: 0.85
  DT:
    - random_state: 241
    - random_state: 42
  LR:
    - C: 0.00001
      penalty: l1
  XGB:
    - n_estimators: 100
      max_depth: 2
      nthread: 4
      gamma: 2
      subsample: 0.2
      colsample_bytree: 0.5
      learning_rate: 2

grid_search:
  fields:
    synthetic:
      - [2]
      - [3]
      - [4]
      - [5]
      - [2, 3]
      - [2, 4]
      - [2, 5]
      - [3, 4]
      - [3, 5]
      - [4, 5]
      - [2, 3, 4]
      - [2, 3, 5]
      - [2, 4, 5]
      - [3, 4, 5]
      - [2, 3, 4, 5]
  classifiers:
    KNN:
      params:
        p: [1,2]
        n_neighbors: [1,3]
        weights: ['distance']
      report_params:
        p: 'p'
        n_neighbors: 'k'
  samplers:
    smote:
      params:
        k: [5, 11, 21]
        ratio: [0.99]
      report_params:
        k: 'smote_k'
        ratio: 'smote_ratio'
    oversampler:
      params:
        count: [100, 500, 1000, 2000]
      report_params:
        count: 'oversampler_count'

influence:
  synthetic: [[2,3,4],[2,3,5],[2,4,5],[3,4,5],[2,5]]
  orbital: [[2,3,4],[2,3,8],[2,4,8],[3,4,8],[2,8]]
system:
  threads: 1
