catalogs:
  synthetic: all.syn
  orbital: allnum.cat
  property: allnum.pro

resonance_tables:
  js: matrix-js.res

librations_folders:
  "4J-2S-1": "4J-2S-1"
  "all-JS": libration_asteroids_JS

classifiers:
  KNN:
    - metric: euclidean
    - metric: knezevic
    - weights: distance
      n_jobs: 1
      algorithm: ball_tree
      p: 2
    - weights: distance
      n_jobs: 1
      algorithm: ball_tree
      metric: knezevic
  GB:
    - n_estimators: 7
      learning_rate: 0.6
      min_samples_split: 150
    - n_estimators: 10
      learning_rate: 0.85
    - n_estimators: 50
      learning_rate: 0.85
  DT:
    - random_state: 241
    - random_state: 42
  LR:
    - C: 0.00001
      penalty: l1
  XGB:
    - n_estimators: 100
      max_depth: 2
      n_thread: 1
      gamma: 0.5
      subsample: 0.1
      colsample_bytree: 0.1
grid_search:
  fields:
    synthetic:
      - [2]
      - [3]
      - [4]
      - [5]
      - [2, 3]
      - [2, 4]
      - [2, 5]
      - [3, 4]
      - [3, 5]
      - [4, 5]
      - [2, 3, 4]
      - [2, 3, 5]
      - [2, 4, 5]
      - [3, 4, 5]
      - [2, 3, 4, 5]
  KNN:
    p: [1,2,3,4,5]
    n_neighbors: [1,3,5,7,11,13,15,17,19,21]
    weights: ['distance']

influence:
  synthetic: [[2,3,4],[2,3,5],[2,4,5],[3,4,5],[2,5]]
  orbital: [[2,3,4],[2,3,8],[2,4,8],[3,4,8],[2,8]]
system:
  threads: 1
